# Generated by Django 5.1 on 2024-08-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateur', '0002_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Nom',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Email',
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
