# Generated by Django 5.1 on 2024-08-24 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateur', '0004_utilisateurpersonnalise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UtilisateurPersonnalise',
        ),
    ]
