# Generated by Django 5.1 on 2024-08-30 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateur', '0005_delete_utilisateurpersonnalise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhtdata',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
