# Generated by Django 5.1 on 2024-09-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateur', '0006_alter_dhtdata_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhtdata',
            name='gaz',
            field=models.FloatField(null=True),
        ),
    ]
