# Generated by Django 5.1 on 2024-09-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateur', '0011_esp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhtdata',
            name='user',
        ),
    ]
