# Generated by Django 5.1 on 2024-09-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateur', '0012_remove_dhtdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhtdata',
            name='esp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Utilisateur.esp'),
        ),
    ]
