# Generated by Django 5.1 on 2024-08-26 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0002_alter_client_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
    ]
