# Generated by Django 5.1 on 2024-09-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DHTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('gaz', models.FloatField(default=0.0, null=True)),
                ('feux', models.CharField(default='N/A', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('esp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrateur.esp')),
            ],
        ),
    ]
