# Generated by Django 5.1 on 2024-10-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0007_remove_esp_esp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='langue_preferée',
            field=models.CharField(default='fr', max_length=10),
        ),
    ]
