# Generated by Django 5.1 on 2024-10-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0008_userprofile_langue_preferée'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='esp',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
