# Generated by Django 5.1 on 2024-10-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrateur', '0011_seuils'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seuils',
            name='gazMax',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seuils',
            name='gazMin',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seuils',
            name='humMax',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seuils',
            name='humMin',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seuils',
            name='tempMax',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='seuils',
            name='tempMin',
            field=models.FloatField(default=0, null=True),
        ),
    ]
